entities:
- name: springboot2_api_service_container_deployment
  namespace: laplacian.arch.deployment.component.springboot2_api_service
  supertype_name: container_deployment
  supertype_namespace: laplacian.arch.deployment.container

  properties:
  - name: http_port
    type: number
    optional: true
    default_value: |
      8080

  - name: enable_jmx
    type: boolean
    optional: true
    default_value: |
      true

  - name: jmx_port
    type: number
    optional: true
    default_value: |
      9010

  - name: enable_debug
    type: boolean
    optional: true
    default_value: |
      false

  - name: debug_port
    type: number
    optional: true
    default_value: |
      5005

  relationships:
  - name: datasources
    reference_entity_name: datasource_configuration
    reference_entity_namespace: laplacian.arch.deployment.datasource
    cardinality: '*'
    aggregate: true

  - name: elasticsearch_clients
    reference_entity_name: elasticsearch_client_configuration
    reference_entity_namespace: laplacian.arch.deployment.component.elasticsearch
    cardinality: '*'
    aggregate: true

